apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: Deployment
      name: my-deployment-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: my-cluster-2-deployment